name: Build and Push to ECR

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
    - name: Lint Dockerfile with Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with: 
        dockerfile: ./Dockerfile
    - name: Build Docker Image
      run: |
        docker build -t myapp:latest .
    - name: Scan the docker image with trivy
      run: |
        trivy image --severity HIGH,CRITICAL myapp:latest
    - name: Push Docker image to Amazon ECR
      run: |
        docker tag myapp:latest ${{steps.login-ecr.outputs.registry}}/myapp:latest
        docker push ${{steps.login-ecr.outputs.registry}}/myapp:latest
        